[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_WHATSAPP_NUMBER,NEXT_PUBLIC_SANITY_PROJECT_ID,BUSINESS_EMAIL"

[[plugins]]
  package = "@netlify/plugin-nextjs"